# Generated by Django 2.0.6 on 2019-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_auto_20190529_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='accessibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='affordability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='safety',
            field=models.IntegerField(default=0),
        ),
    ]
