# Generated by Django 2.0.6 on 2019-05-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0005_locationrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='username',
        ),
    ]
