# Generated by Django 2.0.6 on 2019-06-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0006_auto_20190530_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='location_long',
            field=models.FloatField(default=0),
        ),
    ]
