# Generated by Django 2.0.6 on 2019-06-04 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0007_auto_20190603_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='accessibility',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='affordability',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='date_of_visit',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='safety',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
