# Generated by Django 2.0.6 on 2019-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0008_auto_20190604_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
