# Generated by Django 2.0.6 on 2019-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0009_locationlog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
