# Generated by Django 2.0.6 on 2019-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0010_auto_20190605_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
