# Generated by Django 2.0.6 on 2019-06-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0011_auto_20190605_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='locationrating',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationrating',
            name='userModel_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelApp.UserModel'),
        ),
    ]
