# Generated by Django 2.0.6 on 2019-06-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0012_auto_20190610_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationRating',
            new_name='LocationFavorite',
        ),
    ]
